---
title: "chi-square"
output: html_notebook
---
## With experience
x is observed data
y is past statistical data
```{r}
x <- c(4,6,17,16,8,9)
y <- c(5,5,20,20,10,10)

s = 0
for( i in 1:6){
  s = s+(x[i]-y[i])^2/y[i]
}
df = length(x)-1
print(paste("chi-square: ",s,"df:",df,"p-value",1-pchisq(s,df)))

```


## Even probability (dice)

```{r}
dice <- matrix(c(4,6,17,16,8,9),ncol=6,byrow=TRUE)
colnames(dice) <- c("1","2","3","4","5","6")
rownames(dice) <- c("observed")
dice <- as.table(dice)

print(chisq.test(dice))
dice.chiq = sum((dice-10)^2/10)
dice.df = length(dice)-1
print(paste("chi-square: ",dice.chiq,"df:",dice.df,"p-value",1-pchisq(dice.chiq,dice.df)))

```
## Chi-square test of independence
                  Total
A     80  100 20  200 
B     99  190 96  385 
C     70  30  10  110 
Total 249 320 126 695 
                     Proportion
A     80 100 20 200  200/695 
B     99 190 96 385  385/695 
C     70 30  10 110  110/695 
Total 249 320 126    695

A 80 (71.65) 100 (92.09) 20 (36.26)
B 99 (137.94) 190 (177.27) 96 (69.80)
C 70 (39.41) 30 (50.65) 10 (19.94)

chi-square = sum((80-71.65)^2/71.65+(100-92.09)^2/92.09...)
```{r}
dice <- matrix(c(80, 100, 20,99,190, 96,70,30,10),ncol=3,byrow=TRUE)
colnames(dice) <- c("1","2","3")
rownames(dice) <- c("A","B","C")
dice <- as.table(dice)

print(chisq.test(dice))
print(paste("chi-square: ",sum((dice-10)^2/10),"df: ",2*2))
#df = (row-1)*(col-1)

```