# Generated by Django 3.0.6 on 2020-05-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='char',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='char', to='demo.book'),
        ),
        migrations.CreateModel(
            name='author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('book', models.ManyToManyField(to='demo.book')),
            ],
        ),
    ]
